# Generated by Django 6.0.5 on 2026-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField()),
                ('emp_sal', models.FloatField()),
                ('emp_addr', models.CharField()),
            ],
        ),
    ]
